language: c
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install bc
  - sudo apt-get install python-rdflib python-yaml
#compiler:
#  - clang
#  - gcc
env:
  global:
    - TRAVIS: 1  # affects e.g. codepolicycheck
script:
  - make codepolicycheck
  - make apitest
  - make qecmatest
