--- !ditz.rubyforge.org,2008-03-06/project 
name: duk
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: duk
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.1
  status: :released
  release_time: 2013-02-14 00:00:00 Z
  log_events: 
  - - 2013-02-14 00:00:00 Z
    - sva <sami.vaarala@iki.fi>
    - created
    - ""
  - - 2013-02-14 00:00:00 Z
    - sva <sami.vaarala@iki.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.2
  status: :released
  release_time: 2013-02-27 16:25:31.310841 Z
  log_events: 
  - - 2013-02-17 01:38:12.567901 Z
    - sva <sami.vaarala@iki.fi>
    - created
    - ""
  - - 2013-02-27 16:25:31.310863 Z
    - sva <sami.vaarala@iki.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.3
  status: :released
  release_time: 2013-03-16 19:50:09.615167 Z
  log_events: 
  - - 2013-02-17 01:38:22.089104 Z
    - sva <sami.vaarala@iki.fi>
    - created
    - ""
  - - 2013-03-16 19:50:09.615174 Z
    - sva <sami.vaarala@iki.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.4
  status: :released
  release_time: 2013-03-31 21:58:37.814216 Z
  log_events: 
  - - 2013-02-27 14:50:50.048912 Z
    - sva <sami.vaarala@iki.fi>
    - created
    - ""
  - - 2013-03-31 21:58:37.814237 Z
    - sva <sami.vaarala@iki.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.5
  status: :released
  release_time: 2013-05-23 18:02:18.765167 Z
  log_events: 
  - - 2013-03-02 12:10:01.617306 Z
    - sva <sami.vaarala@iki.fi>
    - created
    - ""
  - - 2013-05-23 18:02:18.765185 Z
    - sva <sami.vaarala@iki.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.6
  status: :released
  release_time: 2013-09-21 18:03:18.650309 Z
  log_events: 
  - - 2013-03-12 22:06:52.926144 Z
    - sva <sami.vaarala@iki.fi>
    - created
    - ""
  - - 2013-09-21 18:03:18.650315 Z
    - sva <sami.vaarala@iki.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.7
  status: :released
  release_time: 2013-10-30 21:31:55.929025 Z
  log_events: 
  - - 2013-07-30 22:33:36.876643 Z
    - sva <sami.vaarala@iki.fi>
    - created
    - ""
  - - 2013-10-30 21:31:55.929049 Z
    - sva <sami.vaarala@iki.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.8
  status: :released
  release_time: 2013-12-18 23:10:46.924131 Z
  log_events: 
  - - 2013-07-30 22:33:49.557961 Z
    - sva <sami.vaarala@iki.fi>
    - created
    - ""
  - - 2013-12-18 23:10:46.924141 Z
    - sva <sami.vaarala@iki.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.9
  status: :released
  release_time: 2014-02-01 23:42:10.578173 Z
  log_events: 
  - - 2013-10-28 22:54:11.773532 Z
    - sva <sami.vaarala@iki.fi>
    - created
    - ""
  - - 2014-02-01 23:42:10.578195 Z
    - sva <sami.vaarala@iki.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.10
  status: :released
  release_time: 2014-04-13 16:39:22.301038 Z
  log_events: 
  - - 2013-10-31 00:05:07.328729 Z
    - sva <sami.vaarala@iki.fi>
    - created
    - ""
  - - 2014-04-13 16:39:22.301067 Z
    - Sami Vaarala <sami.vaarala@iki.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.11
  status: :released
  release_time: 2014-07-11 11:18:31.082115 Z
  log_events: 
  - - 2013-12-25 19:51:32.028204 Z
    - sva <sami.vaarala@iki.fi>
    - created
    - ""
  - - 2014-07-11 11:18:31.082127 Z
    - Sami Vaarala <sami.vaarala@iki.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.12
  status: :released
  release_time: 2014-09-26 12:31:08.571191 Z
  log_events: 
  - - 2014-04-12 13:49:36.896971 Z
    - Sami Vaarala <sami.vaarala@iki.fi>
    - created
    - ""
  - - 2014-09-26 12:31:08.571211 Z
    - Sami Vaarala <sami.vaarala@iki.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v1.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-07-10 12:44:11.203457 Z
    - Sami Vaarala <sami.vaarala@iki.fi>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v1.1
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-07-10 12:44:37.923468 Z
    - Sami Vaarala <sami.vaarala@iki.fi>
    - created
    - ""
