--- !ditz.rubyforge.org,2008-03-06/project 
name: duk
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: duk
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.1
  status: :released
  release_time: 2013-02-14 00:00:00 Z
  log_events: 
  - - 2013-02-14 00:00:00 Z
    - sva <sami.vaarala@poplatek.fi>
    - created
    - ""
  - - 2013-02-14 00:00:00 Z
    - sva <sami.vaarala@poplatek.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.2
  status: :released
  release_time: 2013-02-27 16:25:31.310841 Z
  log_events: 
  - - 2013-02-17 01:38:12.567901 Z
    - sva <sami.vaarala@poplatek.fi>
    - created
    - ""
  - - 2013-02-27 16:25:31.310863 Z
    - sva <sami.vaarala@poplatek.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.3
  status: :released
  release_time: 2013-03-16 19:50:09.615167 Z
  log_events: 
  - - 2013-02-17 01:38:22.089104 Z
    - sva <sami.vaarala@poplatek.fi>
    - created
    - ""
  - - 2013-03-16 19:50:09.615174 Z
    - sva <sami.vaarala@poplatek.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.4
  status: :released
  release_time: 2013-03-31 21:58:37.814216 Z
  log_events: 
  - - 2013-02-27 14:50:50.048912 Z
    - sva <sami.vaarala@poplatek.fi>
    - created
    - ""
  - - 2013-03-31 21:58:37.814237 Z
    - sva <sami.vaarala@poplatek.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.5
  status: :released
  release_time: 2013-05-23 18:02:18.765167 Z
  log_events: 
  - - 2013-03-02 12:10:01.617306 Z
    - sva <sami.vaarala@poplatek.fi>
    - created
    - ""
  - - 2013-05-23 18:02:18.765185 Z
    - sva <sami.vaarala@poplatek.fi>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.6
  status: :unreleased
  release_time: 
  log_events: 
  - - 2013-03-12 22:06:52.926144 Z
    - sva <sami.vaarala@poplatek.fi>
    - created
    - ""
