define: DUK_USE_DATE_GET_NOW
introduced: 1.3.0
default: false
tags:
  - date
  - portability
description: >
  Mandatory macro for getting the current time, see datetime.rst.

  If the time provided experiences time jumps or doesn't advance in realtime
  (which is useful in some time virtualization scenarios), consider defining
  DUK_USE_GET_MONOTONIC_TIME.
