define: DUK_USE_NONSTD_REGEXP_BRACES
feature_enables: DUK_OPT_NONSTD_REGEXP_BRACES
introduced: 1.3.2
default: true
tags:
  - ecmascript
description: >
  Enable support for non-standard '{' literal. Ecmascript requires
  curly braces to be escaped, but most regex engine support them
  when they are not used in valid quantifier. This option is recommended.
