define: DUK_USE_GC_TORTURE
introduced: 1.0.0
default: false
tags:
  - gc
  - memory
  - development
description: >
  Development time option: force full mark-and-sweep on every allocation to
  stress test memory management.
