define: DUK_USE_PACKED_TVAL_POSSIBLE
introduced: 1.0.0
default: false
tags:
  - portability
description: >
  Define when packed, 8-byte duk_tval representation is possible.

# FIXME: a bit pointless, as this is used as an intermediate define only; remove.
