define: DUK_USE_VERBOSE_PROP_ERRORS
feature_enables: DUK_OPT_VERBOSE_PROP_ERRORS
introduced: 1.4.0
default: true
tags:
  - ecmascript
  - sandbox
description: >
  Summarize offending base value and key for property operation errors
  such as "null.foo = 123;".  Base values and keys are summarized using
  duk_push_string_tval_readable().

  The key/value summary includes string data which may be an issue for some
  security critical environments.  Disable this option in such environments.
