define: DUK_USE_UNALIGNED_ACCESSES_POSSIBLE
introduced: 1.0.0
default: false
tags:
  - portability
description: >
  Target architecture unaligned memory accesses (e.g. 32-bit integer access
  from an arbitrary address).

# FIXME: this is just an intermediate define, so remove entirely
