define: DUK_USE_DEBUGGER_THROW_NOTIFY
feature_enables: DUK_OPT_DEBUGGER_THROW_NOTIFY
introduced: 1.4.0
requires:
  - DUK_USE_DEBUGGER_SUPPORT
related:
  - DUK_USE_DEBUGGER_PAUSE_UNCAUGHT
default: false
tags:
  - debugger
description: >
  Send a Throw notify when an error is about to be thrown.  The Throw notify
  also indicates if an error is fatal (most likely not caught) which is very
  useful in debugging.
