# Platform metadata

required_defines:
  # FIXME
  - DUK_USE_PLATFORM_STRING

autodetect:
  # Platforms for autodetect header.  Order matters because some defines
  # overlap, so rules select for more specific define first.
  -
    name: Apple iPhone, OSX, Darwin
    check: DUK_F_APPLE
    include: platform_apple.h.in
  -
    name: OpenBSD
    check: DUK_F_OPENBSD
    include: platform_openbsd.h.in
  -
    name: Generic BSD
    check: DUK_F_BSD
    include: platform_genericbsd.h.in
  -
    name: Atari TOS
    check: DUK_F_TOS
    include: platform_tos.h.in
  -
    name: AmigaOS
    check: DUK_F_AMIGAOS
    include: platform_amigaos.h.in
  -
    name: Windows
    check: DUK_F_WINDOWS
    include: platform_windows.h.in
  -
    name: Flashplayer (Crossbridge)
    check: DUK_F_FLASHPLAYER
    include: platform_flashplayer.h.in
  -
    name: QNX
    check: DUK_F_QNX
    include: platform_qnx.h.in
  -
    name: TI-Nspire
    check: DUK_F_TINSPIRE
    include: platform_tinspire.h.in
  -
    name: Linux
    check: DUK_F_LINUX
    include: platform_linux.h.in
  -
    name: Generic POSIX
    check: DUK_F_POSIX
    include: platform_posix.h.in
  -
    name: Cygwin
    check: DUK_F_CYGWIN
    include: platform_cygwin.h.in
  -
    name: Generic UNIX
    check: null
    include: platform_genericunix.h.in  # if nothing else
